# Site settings
title: Squier.io
email: theo.plockyn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bienvenue sur le site de Squier.qn ( Ou alors SquierDotQn, c'est selon ! ) avec des contributions de Levrifon !
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://squierdotqn.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  SquierDotQn
github_username:  Levrifon

# Build settings
markdown: kramdown
